Recyco/Models/Mission.cs
#pragma warning disable CS8618
using ProjectRecycle.Models;
using ProjectRecycle.Utility;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ProjectRecycle.Models
{
    public class Mission
    {
        [Key]
        public int MissionId { get; set; }
        public int UserId { get; set; }
        public int WasteId { get; set; }
        
        
        

        public StaticData.MissionStatus Status { get; set; } = StaticData.MissionStatus.Pending;
        // Created At
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        // Updated At
        public DateTime UpdatedAt { get; set; } = DateTime.Now;

        //Navigation Properties
        public Waste? Waste { get; set; }
        public AppUser? User { get; set; }

    }
}

Recyco/Controllers/MissionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectRecycle.Models;

namespace ProjectRecycle.Controllers
{
    public class MissionsController : Controller
    {
        private readonly MyContext _context;

        public MissionsController(MyContext context)
        {
            _context = context;
        }

        // GET: Missions
        public async Task<IActionResult> Index()
        {
            var myContext = _context.Missions.Include(m => m.User).Include(m => m.Waste);
            ViewBag.ShowFooter = false;
            return View(await myContext.ToListAsync());
        }

        // GET: Missions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Missions == null)
            {
                return NotFound();
            }

            var mission = await _context.Missions
                .Include(m => m.User)
                .Include(m => m.Waste)
                .FirstOrDefaultAsync(m => m.MissionId == id);
            if (mission == null)
            {
                return NotFound();
            }
            ViewBag.ShowFooter = false;
            return View(mission);
        }

        // GET: Missions/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.AppUsers, "UserId", "Expertise");
            ViewData["WasteId"] = new SelectList(_context.Wastes, "WasteId", "Type");
            ViewData["WasteId2"] = new SelectList(_context.Wastes, "WasteId", "WasteId");
            ViewBag.ShowFooter = false;
            return View();
        }

        // POST: Missions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MissionId,UserId,WasteId,Status,Message,CreatedAt,UpdatedAt")] Mission mission)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mission);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Missions", new { id = HttpContext.Session.GetInt32("adminId") });
            }
            ViewData["UserId"] = new SelectList(_context.AppUsers, "UserId", "UserId", mission.UserId);
            ViewData["WasteId"] = new SelectList(_context.Wastes, "WasteId", "WasteId", mission.WasteId);
            ViewBag.ShowFooter = false;
            return View(mission);
        }

        // GET: Missions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Missions == null)
            {
                return NotFound();
            }

            var mission = await _context.Missions.FindAsync(id);
            if (mission == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.AppUsers, "UserId", "Email", mission.UserId);
            ViewData["WasteId"] = new SelectList(_context.Wastes, "WasteId", "WasteId", mission.WasteId);
            ViewBag.ShowFooter = false;
            return View(mission);
        }

        // POST: Missions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MissionId,UserId,WasteId,Status,Message,CreatedAt,UpdatedAt")] Mission mission)
        {
            if (id != mission.MissionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mission);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MissionExists(mission.MissionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewBag.ShowFooter = false;
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.AppUsers, "UserId", "Email", mission.UserId);
            ViewData["WasteId"] = new SelectList(_context.Wastes, "WasteId", "WasteId", mission.WasteId);
            return View(mission);
        }

        // GET: Missions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Missions == null)
            {
                return NotFound();
            }

            var mission = await _context.Missions
                .Include(m => m.User)
                .Include(m => m.Waste)
                .FirstOrDefaultAsync(m => m.MissionId == id);
            if (mission == null)
            {
                return NotFound();
            }
            ViewBag.ShowFooter = false;
            return View(mission);
        }

        // POST: Missions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Missions == null)
            {
                return Problem("Entity set 'MyContext.Missions'  is null.");
            }
            var mission = await _context.Missions.FindAsync(id);
            if (mission != null)
            {
                _context.Missions.Remove(mission);
            }
            
            await _context.SaveChangesAsync();
            ViewBag.ShowFooter = false;
            return RedirectToAction(nameof(Index));
        }

        private bool MissionExists(int id)
        {
          return (_context.Missions?.Any(e => e.MissionId == id)).GetValueOrDefault();
        }
    }
}

Recyco/Controllers/OffersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectRecycle.Models;
using ProjectRecycle.Utility;

namespace ProjectRecycle.Controllers
{
    public class OffersController : Controller
    {
        private readonly MyContext _context;

        public OffersController(MyContext context)
        {
            _context = context;
        }

        public class MyModel
        {
            public List<Offer> LastSixRecordsByEndDate { get; set; }
            public List<Offer> LastSixRecordsByCreatedAt { get; set; }
            public List<Offer> MostSixPopularRecords { get; set; }
            public List<Offer> AllOffers { get; set; }
        }
        // GET: Offers
        public async Task<IActionResult> Offers()
        {
            var myContext = _context.Offers.Include(o => o.Waste);
            ViewBag.ShowFooter = false;
            return View(await myContext.ToListAsync());
        }
        // GET: Offers
        public IActionResult Index()
        {
            var MyContext = _context.Offers.Include(o => o.Waste);

            var allOffers = _context.Offers.Include(o => o.Waste).ToList();


            var lastSixRecordsByEndDate = _context.Offers.Where(d => d.EndDate > DateTime.Now).Include(o => o.Waste)
            .OrderBy(x => x.EndDate) // Order by the property that determines the order
            .Take(6)
            .ToList();

            var lastSixRecordsByCreatedAt = _context.Offers.Include(o => o.Waste)
            .OrderByDescending(x => x.CreatedAt) // Order by the property that determines the order
            .Take(6)
            .ToList();

            var mostSixPopularRecords = _context.Offers.Include(o => o.Waste)
            .OrderByDescending(x => x.Bids.Count) // Order by the property that determines the order
            .Take(6)
            .ToList();
            //Console.WriteLine($"WASTE0-------- {myContext.ToList()[0].Waste.Title}");

            var myModel = new MyModel
            {
                LastSixRecordsByEndDate = lastSixRecordsByEndDate,
                LastSixRecordsByCreatedAt = lastSixRecordsByCreatedAt,
                MostSixPopularRecords = mostSixPopularRecords,
                AllOffers = allOffers

            };
            
            return View(myModel);
        }

        // GET: Offers/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null || _context.Offers == null)
            {
                return NotFound();
            }

            var offer = _context.Offers
            .Where(o => o.OfferId == id)
            .Include(o => o.Waste)
            .Include(o => o.Bids) // Include the related Bids for the Offer
            .ThenInclude(b => b.Bidder) // Include the related Bidder (Company)
            .FirstOrDefault();
            if (offer == null)
            {
                return NotFound();
            }
            
            return View(offer);
        }
        [HttpPost]
        public async Task<IActionResult> Bid(Bid bid)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bid);
                await _context.SaveChangesAsync();
                return Redirect($"Details/{bid.OfferId}");
            }
            
            return Redirect($"Details/{bid.OfferId}");
        }

        // GET: Offers/Create
        public IActionResult Create()
        {
            ViewData["WasteId"] = new SelectList(_context.Wastes, "WasteId", "Title");
            ViewBag.ShowFooter = false;
            return View();
        }

        // POST: Offers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create(Offer offer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(offer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["WasteId"] = new SelectList(_context.Wastes, "WasteId", "WasteId", offer.WasteId);
            ViewBag.ShowFooter = false;
            return View(offer);
        }

        // GET: Offers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Offers == null)
            {
                return NotFound();
            }

            var offer = await _context.Offers.FindAsync(id);
            if (offer == null)
            {
                return NotFound();
            }
            ViewData["WasteId"] = new SelectList(_context.Wastes, "WasteId", "WasteId", offer.WasteId);
            ViewBag.ShowFooter = false;
            return View(offer);
        }

        // POST: Offers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Offer offer)
        {
            if (id != offer.OfferId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(offer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfferExists(offer.OfferId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["WasteId"] = new SelectList(_context.Wastes, "WasteId", "WasteId", offer.WasteId);
            ViewBag.ShowFooter = false;
            return View(offer);
        }

        // GET: Offers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Offers == null)
            {
                return NotFound();
            }

            var offer = await _context.Offers
                .Include(o => o.Waste)
                .FirstOrDefaultAsync(m => m.OfferId == id);
            if (offer == null)
            {
                return NotFound();
            }
            ViewBag.ShowFooter = false;
            return View(offer);
        }

        // POST: Offers/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Offers == null)
            {
                return Problem("Entity set 'MyContext.Offers'  is null.");
            }
            var offer = await _context.Offers.FindAsync(id);
            if (offer != null)
            {
                _context.Offers.Remove(offer);
            }

            await _context.SaveChangesAsync();
            ViewBag.ShowFooter = false;
            return RedirectToAction(nameof(Index));
        }

        #region APIs
        [HttpGet]
        public IActionResult OffersByCategory(string offerCategory)
        {
            var categoryOffer = StaticData.WasteType.Concrete;
            if (offerCategory is not null)
            {
                IEnumerable<Offer> offersList = _context.Offers.Include(offer => offer.Waste).ToList();
                if (offerCategory.ToLower() == "concrete")
                {
                    categoryOffer = StaticData.WasteType.Concrete;
                    offersList = _context.Offers.
                    Include(offer => offer.Waste).
                    Where(offer => offer.Waste.Type == categoryOffer).ToList();
                }
                else if (offerCategory.ToLower() == "plastic")
                {
                    categoryOffer = StaticData.WasteType.Plastic;
                    offersList = _context.Offers.
                    Include(offer => offer.Waste).
                    Where(offer => offer.Waste.Type == categoryOffer).ToList();
                }
                else if (offerCategory.ToLower() == "paper")
                {
                    categoryOffer = StaticData.WasteType.Paper;
                    offersList = _context.Offers.
                    Include(offer => offer.Waste).
                    Where(offer => offer.Waste.Type == categoryOffer).ToList();
                }
                else if (offerCategory.ToLower() == "metal")
                {
                    categoryOffer = StaticData.WasteType.Metal;
                    offersList = _context.Offers.
                    Include(offer => offer.Waste).
                    Where(offer => offer.Waste.Type == categoryOffer).ToList();
                }
                else if (offerCategory.ToLower() == "hazardous")
                {
                    categoryOffer = StaticData.WasteType.hazardous;
                    offersList = _context.Offers.
                    Include(offer => offer.Waste).
                    Where(offer => offer.Waste.Type == categoryOffer).ToList();
                }else if (offerCategory.ToLower() == "wood")
                {
                    categoryOffer = StaticData.WasteType.Wood;
                    offersList = _context.Offers.
                    Include(offer => offer.Waste).
                    Where(offer => offer.Waste.Type == categoryOffer).ToList();
                }
                //else if (offerCategory.ToLower() == "all")
                //{
                //    offersList = _context.Offers.Include(offer => offer.Waste).ToList();
                //}
                return Json(new { data = offersList });
            }
            else

Recyco/Views/Missions/Create.cshtml
@model ProjectRecycle.Models.Mission

@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int? adminId = (int)Context.Session.GetInt32("adminId");

}
<head>
    <!--~ Link CSS  -->
    <link rel="stylesheet" href="~/css/Dashboard.css">
    <!--~ Link BOOTSTRAP  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <!--~ Link Boxicons  -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>


</head>
<body>
    @await Html.PartialAsync("_SideBarAdmin")
    <section class="dashboard">
        <div class="top d-flex justify-content-between">
            <div></div>
            <div class="top-links align-content-end">
                <a asp-area="" class="text-dark" asp-controller="Home" asp-action="Index">Home</a>
                <a asp-area="" class="text-dark" asp-controller="Offers" asp-action="Index">Explore</a>
            </div>

            <div class="Btn" style="background-color:#427D9D;">

                <div class="sign"><svg viewBox="0 0 512 512"><path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z"></path></svg></div>

                <form asp-action="Logout" asp-controller="AppUsers" method="post">
                    <button type="submit" class="btn shadow-none border-0 text-white" style="background-color:#427D9D;">Logout</button>
                </form>
            </div>
        </div>
        <div class="dash-content">
            <div class="overview">
                <div class="title">
                    <span class="text1">Mission Manage</span>
                </div>
            </div>
                    <div class="card shadow-lg p-5 my-2 col-5">
                        <div>
                            <div>
                                <form asp-action="Create">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group mb-2">
                                        <label asp-for="UserId" class="control-label">Consultant By Expertise</label>
                                        <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                                    </div>
                                    <div class="form-group mb-2">
                                        <label asp-for="WasteId" class="control-label">Waste Type</label>
                                <select asp-for="WasteId" class="form-control" asp-items="ViewBag.WasteId" id="wasteIdSelect"></select>
                                    </div>
                            <div class="form-group mb-2" id="selectedWasteIdDisplay">Selected Waste ID: <span id="selectedWasteId"></span></div>
                                    <div class="form-group mb-2">
                                        <label asp-for="Status" class="control-label"></label>
                                        <select asp-for="Status" class="form-control">
                                            <option value="0">
                                                Pending
                                            </option>
                                            <option value="1">Approved</option>
                                            <option value="2">Completed</option>
                                            <option value="3">Rejected</option>
                                        </select>


                                    </div>
                                    <div class="form-group mb-2">
                                        <input type="submit" value="Create" class="btn btn-primary" />
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div>
                            <a asp-action="Index">Back to List</a>
                        </div>
                    </div>
                </div>
            
    </section>

    <script src="~/js/Dashboard.js"></script>
    <script type="module" src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script nomodule src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script>
        document.getElementById('wasteIdSelect').addEventListener('change', function () {
            var selectedWasteId = this.value;
            document.getElementById('selectedWasteId').textContent = selectedWasteId;
        });
    </script>

</body>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Recyco/Views/Missions/Delete.cshtml
@model ProjectRecycle.Models.Mission
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int? adminId = (int)Context.Session.GetInt32("adminId");

}
<head>
    <!--~ Link CSS  -->
    <link rel="stylesheet" href="~/css/Dashboard.css">
    <!--~ Link BOOTSTRAP  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <!--~ Link Boxicons  -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>


</head>
<body>
    @await Html.PartialAsync("_SideBarAdmin")
    <section class="dashboard">
        <div class="top d-flex justify-content-between">
            <div></div>
            <div class="top-links align-content-end">
                <a asp-area="" class="text-dark" asp-controller="Home" asp-action="Index">Home</a>
                <a asp-area="" class="text-dark" asp-controller="Offers" asp-action="Index">Explore</a>
            </div>

            <div class="Btn" style="background-color:#427D9D;">

                <div class="sign"><svg viewBox="0 0 512 512"><path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z"></path></svg></div>

                <form asp-action="Logout" asp-controller="AppUsers" method="post">
                    <button type="submit" class="btn shadow-none border-0 text-white" style="background-color:#427D9D;">Logout</button>
                </form>
            </div>
        </div>
        <div class="dash-content">
            <div class="overview">
                <div class="title">
                    <span class="text1">Mission Manage</span>
                </div>
            </div>
            <div class="card shadow-lg p-5 my-2 col-5">
                <div>
                    <dl>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Status)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Status)
                    </dd>
                    
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.CreatedAt)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.CreatedAt)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.UpdatedAt)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.UpdatedAt)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Waste)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Waste.WasteId)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.User)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.User.Email)
                    </dd>

                    </dl>
                </div>
            </div>
                <div>
                <form asp-action="Delete">
                    <input type="hidden" asp-for="MissionId" />
                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                    <a asp-action="Index">Back to List</a>
                </form>
            </div>
        </div>
    </section>

    <script src="~/js/Dashboard.js"></script>
    <script type="module" src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script nomodule src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>


</body>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Recyco/Views/Missions/Details.cshtml
@model ProjectRecycle.Models.Mission
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int? adminId = (int)Context.Session.GetInt32("adminId");

}
<head>
    <!--~ Link CSS  -->
    <link rel="stylesheet" href="~/css/Dashboard.css">
    <!--~ Link BOOTSTRAP  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <!--~ Link Boxicons  -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>


</head>
<body>
    @await Html.PartialAsync("_SideBarAdmin")
    <section class="dashboard">
        <div class="top d-flex justify-content-between">
            <div></div>
            <div class="top-links align-content-end">
                <a asp-area="" class="text-dark" asp-controller="Home" asp-action="Index">Home</a>
                <a asp-area="" class="text-dark" asp-controller="Offers" asp-action="Index">Explore</a>
            </div>

            <div class="Btn" style="background-color:#427D9D;">

                <div class="sign"><svg viewBox="0 0 512 512"><path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z"></path></svg></div>

                <form asp-action="Logout" asp-controller="AppUsers" method="post">
                    <button type="submit" class="btn shadow-none border-0 text-white" style="background-color:#427D9D;">Logout</button>
                </form>
            </div>
        </div>
        <div class="dash-content">
            <div class="overview">
                <div class="title">
                    <span class="text1">Mission Manage</span>
                </div>
            </div>
            <div class="card shadow-lg p-5 my-2 col-5">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Status)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Status)
                    </dd>
                    
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.CreatedAt)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.CreatedAt)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.UpdatedAt)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.UpdatedAt)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Waste)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Waste.WasteId)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.User)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.User.Email)
                    </dd>
                </dl>
            </div>
            <div>
                <a asp-action="Edit" asp-route-id="@Model?.MissionId">Edit</a> |
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
    </section>

    <script src="~/js/Dashboard.js"></script>
    <script type="module" src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script nomodule src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>


</body>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}