Recyco/Models/AppUser.cs
#pragma warning disable CS8618
using ProjectRecycle.Utility;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ProjectRecycle.Models
{
    public class AppUser
    {
        [Key]
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        // Email
        [Required(ErrorMessage = "Please enter your email.")]
        [EmailAddress(ErrorMessage = "Please enter a valid email.")]
        public string Email { get; set; }

        // Password
        [Required(ErrorMessage = "Please enter your password.")]
        [DataType(DataType.Password)] // useful
        [MinLength(6, ErrorMessage = "Please enter a valid Password .")]
        public string Password { get; set; }

        // Confirm Password
        [NotMapped]
        [Required(ErrorMessage = "Please enter your password.")]
        [Compare("Password", ErrorMessage = "Passwords must match.")]
        [DataType(DataType.Password)] // useful
        [Display(Name = "Confirm Password ")]
        public string ConfirmPassword { get; set; }



        public StaticData.UserRole Role { get; set; }
        public string Diploma { get; set; }
        public string Expertise { get; set; }
        // Created At
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        // Updated At
        public DateTime UpdatedAt { get; set; } = DateTime.Now;
        public List<Mission> Missions { get; set; } = new();
    }
}

Recyco/Controllers/AppUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectRecycle.Models;
using ProjectRecycle.Utility;

namespace ProjectRecycle.Controllers
{
    public class AppUsersController : Controller
    {
        private readonly MyContext _context;

        public AppUsersController(MyContext context)
        {
            _context = context;
        }

        // GET: AppUsers
        public async Task<IActionResult> ErrorPage()
        {
            return View(await _context.AppUsers.ToListAsync());
                        
        }


        #region Admin
        public IActionResult Dashboard()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return RedirectToAction("ErrorPage");
            }
            
            
            int wastes = _context.Wastes.Count();
            int companies = _context.Companies.Count();
            int offers = _context.Offers.Count();
            int bids = _context.Bids.Count();

            ViewBag.Bids = bids;
            ViewBag.Wastes = wastes;
            ViewBag.Companies = companies;
            ViewBag.Offers = offers;

            var dashboard = _context.Companies;
            ViewBag.ShowFooter = false;
            return View(dashboard);

        }
        public async Task<IActionResult> AllOfferAsync()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return RedirectToAction("ErrorPage");
            }
            var myContext = _context.Offers.Include(o => o.Waste).ThenInclude(w=>w.Owner);
            ViewBag.ShowFooter = false;
            return View(await myContext.ToListAsync());
        }

        public async Task<IActionResult> AllWasteAsync()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return RedirectToAction("ErrorPage");
            }
            var myContext = _context.Wastes.Include(c => c.Owner).Include(o => o.Validation).ThenInclude(v=>v.User);
            ViewBag.ShowFooter = false;
            return View(await myContext.ToListAsync());
        }

        public async Task<IActionResult> AllCompanies()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return RedirectToAction("ErrorPage");
            }
            ViewBag.ShowFooter = false;
            return View(await _context.Companies.ToListAsync());
        }

        public async Task<IActionResult> AllUsers()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return RedirectToAction("ErrorPage");
            }
            ViewBag.ShowFooter = false;
            return _context.AppUsers != null ?
                        View(await _context.AppUsers.ToListAsync()) :
                        Problem("Entity set 'MyContext.AppUsers'  is null.");
        }

        // GET: AppUsers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return RedirectToAction("ErrorPage");
            }
            if (id == null || _context.AppUsers == null)
            {
                return NotFound();
            }

            var appUser = await _context.AppUsers
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (appUser == null)
            {
                return NotFound();
            }
            ViewBag.ShowFooter = false;
            return View(appUser);
        }
        // GET: AppUsers/Create
        public IActionResult Create()
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return RedirectToAction("ErrorPage");
            }
            ViewBag.ShowFooter = false;
            return View();
        }

        // POST: AppUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public IActionResult Register(AppUser newUser)
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return RedirectToAction("ErrorPage");
            }
            if (ModelState.IsValid)
            {
                // Email Exist ?
                if (_context.AppUsers.Any(u => u.Email == newUser.Email))
                {
                    // True
                    ModelState.AddModelError("Email", "Email already in use .");
                    return View("LoginPage");
                }
                else
                {
                    // False
                    // 1 - Hash Password
                    PasswordHasher<AppUser> Hasher = new PasswordHasher<AppUser>();
                    newUser.Password = Hasher.HashPassword(newUser, newUser.Password);
                    // 2 - Add 
                    _context.Add(newUser);
                    // 3 - Save
                    _context.SaveChanges();
                    HttpContext.Session.SetInt32("userId", newUser.UserId);
                    HttpContext.Session.SetString("username", newUser.FirstName);
                    // HttpContext.Session.
                    return RedirectToAction("AllUsers", new { id = newUser.UserId });
                }
            }

            return View("LoginPage");
        }


        // GET: AppUsers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return RedirectToAction("ErrorPage");
            }
            if (id == null || _context.AppUsers == null)
            {
                return NotFound();
            }

            var appUser = await _context.AppUsers
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (appUser == null)
            {
                return NotFound();
            }
            ViewBag.ShowFooter = false;
            return View(appUser);
        }

        // POST: AppUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (HttpContext.Session.GetInt32("adminId") == null)
            {
                return RedirectToAction("ErrorPage");
            }
            if (_context.AppUsers == null)
            {
                return Problem("Entity set 'MyContext.AppUsers'  is null.");
            }
            var appUser = await _context.AppUsers.FindAsync(id);
            if (appUser != null)
            {
                _context.AppUsers.Remove(appUser);
            }
            ViewBag.ShowFooter = false;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppUserExists(int id)
        {
            
            return (_context.AppUsers?.Any(e => e.UserId == id)).GetValueOrDefault();
        }
        #endregion

        #region Consultant
        //----------------------------------------------------------------Start Consultant Pages--------------------------------------------->
        //--------------------------Update the mission status---->
        [HttpPost]
        public IActionResult UpdateMissionStatus(int missionId, string newStatus)
        {
            var mission = _context.Missions.Find(missionId);

            if (mission != null)
            {

                mission.Status = Enum.Parse<StaticData.MissionStatus>(newStatus);

                _context.SaveChanges();
            }
            ViewBag.ShowFooter = false;
            return RedirectToAction("ConsultWaste", new { id = mission.UserId });
        }
        // GET: AppUsers/Consultant/5
        [HttpGet("AppUsers/Consultant/{id}")]
        public async Task<IActionResult> Consultant(int? id)

        {
            if (HttpContext.Session.GetInt32("consultantId") == null)
            {
                return RedirectToAction("ErrorPage");
            }
            if (id == null || _context.AppUsers == null)
            {
                return NotFound();
            }

            var appUser = await _context.AppUsers
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (appUser == null)
            {
                return NotFound();
            }
            ViewBag.ShowFooter = false;
            return View(appUser);
        }


        // GET: AppUsers/ConsultWastes/5
        [HttpGet("AppUsers/ConsultWastes/{id}")]
        public async Task<IActionResult> ConsultWaste(int? id)
        {
            if (HttpContext.Session.GetInt32("consultantId") == null)
            {
                return RedirectToAction("ErrorPage");
            }
            if (id == null || _context.AppUsers == null)
            {
                return NotFound();
            }

            var appUser = await _context.AppUsers
                .Include(u => u.Missions).ThenInclude(m => m.Waste).ThenInclude(m => m.Owner)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (appUser == null)
            {
                return NotFound();
            }
            ViewBag.ShowFooter = false;
            return View(appUser);
        }

        public FileResult DownloadFile(string fileName)
        {
            //Build the File Path.
            string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads");
            string filepath = Path.Combine(uploadsFolder, fileName);

            //Read the File data into Byte Array.
            byte[] bytes = System.IO.File.ReadAllBytes(filepath);

Recyco/Views/AppUsers/AllCompanies.cshtml
@model IEnumerable<ProjectRecycle.Models.Company>

@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int? adminId = (int)Context.Session.GetInt32("adminId");

}
<head>
    <!--~ Link CSS  -->
    <link rel="stylesheet" href="~/css/Dashboard.css">
    <!--~ Link BOOTSTRAP  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <!--~ Link Boxicons  -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>


</head>
<body>
@await Html.PartialAsync("_SideBarAdmin")
<section class="dashboard">
    <div class="top d-flex justify-content-between">
        <div></div>
        <div class="top-links align-content-end">
            <a asp-area="" class="text-dark" asp-controller="Home" asp-action="Index">Home</a>
            <a asp-area="" class="text-dark" asp-controller="Offers" asp-action="Index">Explore</a>
        </div>

        <div class="Btn" style="background-color:#427D9D;">

            <div class="sign"><svg viewBox="0 0 512 512"><path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z"></path></svg></div>

            <form asp-action="Logout" asp-controller="AppUsers" method="post">
                <button type="submit" class="btn shadow-none border-0 text-white" style="background-color:#427D9D;">Logout</button>
            </form>
        </div>
    </div>
    <div class="dash-content">
        <div class="overview">
            <div class="title">
                <span class="text1">Companies</span>
            </div>
        </div>

        <table class="table shadow-lg">
            <thead class="table-secondary">
                <tr>
                    <th>Company ID</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Phone number</th>
                    <th>Email</th>
                    <th>Activity</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var company in Model)
                {
                    <tr>
                        <td>@company.CompanyId</td>
                        <td>@company.Name</td>
                        <td>@company.Address</td>
                        <td>@company.PhoneNumber</td>
                        <td>@company.Email</td>
                        <td>@company.ActivityType</td>
                    </tr>
                }
            </tbody>
        </table>

    </div>

</section>

<script src="~/js/Dashboard.js"></script>
<script type="module" src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
<script nomodule src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>


</body>

Recyco/Views/AppUsers/AllOffer.cshtml
@model IEnumerable<ProjectRecycle.Models.Offer>

@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int? adminId = (int)Context.Session.GetInt32("adminId");

}
<head>
    <!--~ Link CSS  -->
    <link rel="stylesheet" href="~/css/Dashboard.css">
    <!--~ Link BOOTSTRAP  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <!--~ Link Boxicons  -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>


</head>
<body>
    @await Html.PartialAsync("_SideBarAdmin")
    <section class="dashboard">
        <div class="top d-flex justify-content-between">
            <div></div>
            <div class="top-links align-content-end">
                <a asp-area="" class="text-dark" asp-controller="Home" asp-action="Index">Home</a>
                <a asp-area="" class="text-dark" asp-controller="Offers" asp-action="Index">Explore</a>
            </div>

            <div class="Btn" style="background-color:#427D9D;">

                <div class="sign"><svg viewBox="0 0 512 512"><path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z"></path></svg></div>

                <form asp-action="Logout" asp-controller="AppUsers" method="post">
                    <button type="submit" class="btn shadow-none border-0 text-white" style="background-color:#427D9D;">Logout</button>
                </form>
            </div>
        </div>
        <div class="dash-content">
            <div class="overview">
                <div class="title">
                    <span class="text1">Offers</span>
                </div>
            </div>
            <table class="table shadow-lg">
                <thead class="table-secondary">
                <tr>
                    <th>Offer ID</th>
                    <th>Title</th>
                    <th>Company Name</th>
                    <th>Price</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var offer in Model)
                {
                    <tr>
                        <td>@offer.OfferId</td>
                        <td>@offer.Waste.Title</td>
                        <td>@offer.Waste.Owner.Name</td>
                        <td>@offer.Waste.Price</td>
                    </tr>
                }
            </tbody>
        </table>

    </div>

    </section>

    <script src="~/js/Dashboard.js"></script>
    <script type="module" src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script nomodule src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>


</body>

Recyco/Views/AppUsers/AllUsers.cshtml
@model IEnumerable<ProjectRecycle.Models.AppUser>

@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int? adminId = (int)Context.Session.GetInt32("adminId");

}

<head>
    <!--~ Link CSS  -->
    <link rel="stylesheet" href="~/css/Dashboard.css">
    <!--~ Link BOOTSTRAP  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <!--~ Link Boxicons  -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>


</head>
<body>
    @await Html.PartialAsync("_SideBarAdmin")
    <section class="dashboard">
        <div class="top d-flex justify-content-between">
            <div></div>
            <div class="top-links align-content-end">
                <a asp-area="" class="text-dark" asp-controller="Home" asp-action="Index">Home</a>
                <a asp-area="" class="text-dark" asp-controller="Offers" asp-action="Index">Explore</a>
            </div>

            <div class="Btn" style="background-color:#427D9D;">

                <div class="sign"><svg viewBox="0 0 512 512"><path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z"></path></svg></div>

                <form asp-action="Logout" asp-controller="AppUsers" method="post">
                    <button type="submit" class="btn shadow-none border-0 text-white" style="background-color:#427D9D;">Logout</button>
                </form>
            </div>
        </div>
        <div class="dash-content">
            <div class="overview">
                <div class="title">
                    <span class="text1">Users</span>
                </div>
            </div>
        <hr />
        <a class="btn btn-info" asp-area="" asp-controller="AppUsers" asp-action="Create">Create new User</a>

            <table class="table shadow-lg">
                <thead class="table-secondary">
                <tr>
                    <th>User ID</th>
                    <th>Name</th>
                    <th>Role</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model)
                {
                    <tr>
                        <td>@user.UserId</td>
                        <td>@user.FirstName  @user.LastName</td>
                        <td>@user.Role</td>
                        <td>
                            <a class="btn btn-info" asp-area="" asp-controller="AppUsers" asp-action="Edit" asp-route-id="@user.UserId">Edit</a>
                            @if (@user.UserId != adminId)
                            {
                                <a class="btn btn-danger" asp-area="" asp-controller="AppUsers" asp-action="Delete" asp-route-id="@user.UserId">Delete</a>

                            }

                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>

    </section>

    <script src="~/js/Dashboard.js"></script>
    <script type="module" src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script nomodule src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>


</body>

Recyco/Views/AppUsers/AllWaste.cshtml
@model IEnumerable<ProjectRecycle.Models.Waste>

@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int? adminId = (int)Context.Session.GetInt32("adminId");
}

<head>
    <!--~ Link CSS  -->
    <link rel="stylesheet" href="~/css/Dashboard.css">
    <!--~ Link BOOTSTRAP  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <!--~ Link Boxicons  -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>


</head>
<body>
    @await Html.PartialAsync("_SideBarAdmin")
    <section class="dashboard">
        <div class="top d-flex justify-content-between">
            <div></div>
            <div class="top-links align-content-end">
                <a asp-area="" class="text-dark" asp-controller="Home" asp-action="Index">Home</a>
                <a asp-area="" class="text-dark" asp-controller="Offers" asp-action="Index">Explore</a>
            </div>

            <div class="Btn" style="background-color:#427D9D;">

                <div class="sign"><svg viewBox="0 0 512 512"><path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z"></path></svg></div>

                <form asp-action="Logout" asp-controller="AppUsers" method="post">
                    <button type="submit" class="btn shadow-none border-0 text-white" style="background-color:#427D9D;">Logout</button>
                </form>
            </div>
        </div>
        <div class="dash-content">
            <div class="overview">
                <div class="title">
                    <span class="text1 ">Wastes</span>
                </div>
            </div>
            <table class="table shadow-lg">
                <thead class="table-secondary">
                <tr>
                    <th>Offer ID</th>
                    <th>Title</th>
                    <th>Company Name</th>
                    <th>Price</th>
                    <th>Status</th>
                    <th>Assigned consultant</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var waste in Model)
                {
                    <tr>
                        <td>@waste.WasteId</td>
                        <td>@waste.Title</td>
                        <td>@waste?.Owner.Name</td>
                        <td>@waste.Price</td>
                        @if (@waste.Validation is null)
                        {
                            <td>Not Assigned</td>
                        }
                        else
                        {
                            <td>@waste.Validation.Status</td>
                        }
                        @if (@waste.Validation is null)
                        {
                            <td>Not Assigned</td>
                        }
                        else
                        {
                            <td>@waste.Validation.User.FirstName  @waste.Validation.User.LastName</td>
                        }
                        
                    </tr>
                }
            </tbody>
        </table>
        <a asp-controller="Missions" asp-action="Create">Make Mission</a>

    </div>

    </section>

    <script src="~/js/Dashboard.js"></script>
    <script type="module" src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script nomodule src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>


</body>

Recyco/Views/AppUsers/ConsultOffre.cshtml
@model ProjectRecycle.Models.AppUser

@{
    ViewData["Title"] = "ConsultOffre";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int? consultantId = (int)Context.Session.GetInt32("consultantId");
}

<head>
    <!--~ Link CSS  -->
    <link rel="stylesheet" href="~/css/Dashboard.css">
    <!--~ Link BOOTSTRAP  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <!--~ Link Boxicons  -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>


</head>
<body>
    @await Html.PartialAsync("_SideBarCons")
    <section class="dashboard">
        <div class="top d-flex justify-content-between">
            <div></div>
            <div class="top-links align-content-end">
                <a asp-area="" class="text-dark" asp-controller="Home" asp-action="Index">Home</a>
                <a asp-area="" class="text-dark" asp-controller="Offers" asp-action="Index">Explore</a>
            </div>

            <div class="Btn" style="background-color:#427D9D;">

                <div class="sign"><svg viewBox="0 0 512 512"><path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z"></path></svg></div>

                <form asp-action="Logout" asp-controller="AppUsers" method="post">
                    <button type="submit" class="btn shadow-none border-0 text-white" style="background-color:#427D9D;">Logout</button>
                </form>
            </div>
        </div>
        <div class="dash-content">
            <div class="overview">
                <div class="title">
                    <span class="text1">Approved Waste</span>
                </div>
            </div>
            <table class="table shadow-lg">
                <thead class="table-secondary">
                <tr>
                    <th>Waste ID</th>
                    <th>Title</th>
                    <th>Company Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var waste in (List<ProjectRecycle.Models.Waste>)ViewData["ApprovedWastes"])
                {
                    <tr>
                        <td>@waste.WasteId</td>
                        <td>@waste.Title</td>
                        <td>@waste.Owner.Name</td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
                <a class="btn text-white" style="background-color:#427D9D;" asp-area="" asp-controller="Offers" asp-action="Create">Create Offer</a>
        </div>


    </div>

    </section>

    <script src="~/js/Dashboard.js"></script>
    <script type="module" src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script nomodule src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>


</body>

Recyco/Views/AppUsers/ErrorPage.cshtml
<body>
    <div class="d-flex align-items-center justify-content-center vh-100">
        <div class="text-center">
            <h1 class="display-1 fw-bold">404</h1>
            <p class="fs-3"> <span class="text-danger">Opps!</span> Page not found.</p>
            <p class="lead">
                The page you’re looking for doesn’t exist.
            </p>
            <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Go Home</a>
        </div>
    </div>
</body>